### PR TITLE
Added tilesheets and added a credits.txt file

### PR DESCRIPTION
**Pull request by Voluptua**
Basically what the title says. I've just collected a few tilesheets and listed all the artist in the credits.txt file. The names of the images are just numbers from 1 to 20 and in the credits.txt, the file looks like this: ```1: Artist1,Artist2```. 

Note: I dont know if all tiles are 16x16 pixels tall, maybe there are some which are 32x32 pixels tall.

### CODE REVIEW

**Comment by PCG06** [comment]
This is my first pull request comment. Hello world!

**Comment by Voluptua** [comment]
This is my first pull request, Hello World!

**Review by PCG06 — COMMENTED** [review]
The tiles are nice. But do any of the people in the credits list have any socials?
Also rename the file to README and make it a markdown so that it'll be shown when you click on the folder

**Comment by jmynes** [comment]
Sorry, didn't mean to reference this PR, using `#3` in my commit message accidentally mentioned this commit 😅

**Pull request closed without merging**
